services:
  - type: web
    name: raex-university-predictor
    env: python
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app/main.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"